// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { Comments, Default, type Options, Posts, Users } from '../sdk.gen';
import type { CreateCommentData, CreateCommentError, CreateCommentResponse, CreatePostData, CreatePostError, CreatePostResponse, CreateUserData, CreateUserError, CreateUserResponse, DeleteCommentData, DeleteCommentError, DeleteCommentResponse, DeletePostData, DeletePostError, DeletePostResponse, DeleteUserData, DeleteUserError, DeleteUserResponse, GetCommentData, GetCommentError, GetCommentResponse, GetPostData, GetPostError, GetPostResponse, GetUserData, GetUserError, GetUserResponse, HealthData, HealthResponse, ListCommentsData, ListCommentsResponse, ListPostsData, ListPostsResponse, ListUsersData, ListUsersResponse, UpdateCommentData, UpdateCommentError, UpdateCommentResponse, UpdatePostData, UpdatePostError, UpdatePostResponse, UpdateUserData, UpdateUserError, UpdateUserResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * List Users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, DefaultError, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Users.listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

/**
 * Create User
 */
export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<CreateUserResponse, CreateUserError, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<CreateUserResponse, CreateUserError, Options<CreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Users.createUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<DeleteUserResponse, DeleteUserError, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserResponse, DeleteUserError, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Users.deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get User
 */
export const getUserOptions = (options: Options<GetUserData>) => queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Users.getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

/**
 * Update User
 */
export const updateUserMutation = (options?: Partial<Options<UpdateUserData>>): UseMutationOptions<UpdateUserResponse, UpdateUserError, Options<UpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserResponse, UpdateUserError, Options<UpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Users.updateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listPostsQueryKey = (options?: Options<ListPostsData>) => createQueryKey('listPosts', options);

/**
 * List Posts
 */
export const listPostsOptions = (options?: Options<ListPostsData>) => queryOptions<ListPostsResponse, DefaultError, ListPostsResponse, ReturnType<typeof listPostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Posts.listPosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listPostsQueryKey(options)
});

/**
 * Create Post
 */
export const createPostMutation = (options?: Partial<Options<CreatePostData>>): UseMutationOptions<CreatePostResponse, CreatePostError, Options<CreatePostData>> => {
    const mutationOptions: UseMutationOptions<CreatePostResponse, CreatePostError, Options<CreatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Posts.createPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Post
 */
export const deletePostMutation = (options?: Partial<Options<DeletePostData>>): UseMutationOptions<DeletePostResponse, DeletePostError, Options<DeletePostData>> => {
    const mutationOptions: UseMutationOptions<DeletePostResponse, DeletePostError, Options<DeletePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Posts.deletePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPostQueryKey = (options: Options<GetPostData>) => createQueryKey('getPost', options);

/**
 * Get Post
 */
export const getPostOptions = (options: Options<GetPostData>) => queryOptions<GetPostResponse, GetPostError, GetPostResponse, ReturnType<typeof getPostQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Posts.getPost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostQueryKey(options)
});

/**
 * Update Post
 */
export const updatePostMutation = (options?: Partial<Options<UpdatePostData>>): UseMutationOptions<UpdatePostResponse, UpdatePostError, Options<UpdatePostData>> => {
    const mutationOptions: UseMutationOptions<UpdatePostResponse, UpdatePostError, Options<UpdatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Posts.updatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listCommentsQueryKey = (options?: Options<ListCommentsData>) => createQueryKey('listComments', options);

/**
 * List Comments
 */
export const listCommentsOptions = (options?: Options<ListCommentsData>) => queryOptions<ListCommentsResponse, DefaultError, ListCommentsResponse, ReturnType<typeof listCommentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Comments.listComments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listCommentsQueryKey(options)
});

/**
 * Create Comment
 */
export const createCommentMutation = (options?: Partial<Options<CreateCommentData>>): UseMutationOptions<CreateCommentResponse, CreateCommentError, Options<CreateCommentData>> => {
    const mutationOptions: UseMutationOptions<CreateCommentResponse, CreateCommentError, Options<CreateCommentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Comments.createComment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Comment
 */
export const deleteCommentMutation = (options?: Partial<Options<DeleteCommentData>>): UseMutationOptions<DeleteCommentResponse, DeleteCommentError, Options<DeleteCommentData>> => {
    const mutationOptions: UseMutationOptions<DeleteCommentResponse, DeleteCommentError, Options<DeleteCommentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Comments.deleteComment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCommentQueryKey = (options: Options<GetCommentData>) => createQueryKey('getComment', options);

/**
 * Get Comment
 */
export const getCommentOptions = (options: Options<GetCommentData>) => queryOptions<GetCommentResponse, GetCommentError, GetCommentResponse, ReturnType<typeof getCommentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Comments.getComment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCommentQueryKey(options)
});

/**
 * Update Comment
 */
export const updateCommentMutation = (options?: Partial<Options<UpdateCommentData>>): UseMutationOptions<UpdateCommentResponse, UpdateCommentError, Options<UpdateCommentData>> => {
    const mutationOptions: UseMutationOptions<UpdateCommentResponse, UpdateCommentError, Options<UpdateCommentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Comments.updateComment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Health
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse, DefaultError, HealthResponse, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Default.health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});
