// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePostData, CreatePostErrors, CreatePostResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeletePostData, DeletePostErrors, DeletePostResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, GetPostData, GetPostErrors, GetPostResponses, GetUserData, GetUserErrors, GetUserResponses, HealthData, HealthResponses, ListPostsData, ListPostsResponses, ListUsersData, ListUsersResponses, UpdatePostData, UpdatePostErrors, UpdatePostResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses } from './types.gen';
import { zCreatePostResponse, zCreateUserResponse, zDeletePostResponse, zDeleteUserResponse, zGetPostResponse, zGetUserResponse, zHealthResponse, zListPostsResponse, zListUsersResponse, zUpdatePostResponse, zUpdateUserResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Users {
    /**
     * List Users
     */
    public static listUsers<ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
            responseValidator: async (data) => await zListUsersResponse.parseAsync(data),
            url: '/users',
            ...options
        });
    }
    
    /**
     * Create User
     */
    public static createUser<ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> {
        return (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
            responseValidator: async (data) => await zCreateUserResponse.parseAsync(data),
            url: '/users',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete User
     */
    public static deleteUser<ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> {
        return (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
            responseValidator: async (data) => await zDeleteUserResponse.parseAsync(data),
            url: '/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Get User
     */
    public static getUser<ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError> {
        return (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
            responseValidator: async (data) => await zGetUserResponse.parseAsync(data),
            url: '/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Update User
     */
    public static updateUser<ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> {
        return (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
            responseValidator: async (data) => await zUpdateUserResponse.parseAsync(data),
            url: '/users/{user_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Posts {
    /**
     * List Posts
     */
    public static listPosts<ThrowOnError extends boolean = false>(options?: Options<ListPostsData, ThrowOnError>): RequestResult<ListPostsResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<ListPostsResponses, unknown, ThrowOnError>({
            responseValidator: async (data) => await zListPostsResponse.parseAsync(data),
            url: '/posts',
            ...options
        });
    }
    
    /**
     * Create Post
     */
    public static createPost<ThrowOnError extends boolean = false>(options: Options<CreatePostData, ThrowOnError>): RequestResult<CreatePostResponses, CreatePostErrors, ThrowOnError> {
        return (options.client ?? client).post<CreatePostResponses, CreatePostErrors, ThrowOnError>({
            responseValidator: async (data) => await zCreatePostResponse.parseAsync(data),
            url: '/posts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Post
     */
    public static deletePost<ThrowOnError extends boolean = false>(options: Options<DeletePostData, ThrowOnError>): RequestResult<DeletePostResponses, DeletePostErrors, ThrowOnError> {
        return (options.client ?? client).delete<DeletePostResponses, DeletePostErrors, ThrowOnError>({
            responseValidator: async (data) => await zDeletePostResponse.parseAsync(data),
            url: '/posts/{post_id}',
            ...options
        });
    }
    
    /**
     * Get Post
     */
    public static getPost<ThrowOnError extends boolean = false>(options: Options<GetPostData, ThrowOnError>): RequestResult<GetPostResponses, GetPostErrors, ThrowOnError> {
        return (options.client ?? client).get<GetPostResponses, GetPostErrors, ThrowOnError>({
            responseValidator: async (data) => await zGetPostResponse.parseAsync(data),
            url: '/posts/{post_id}',
            ...options
        });
    }
    
    /**
     * Update Post
     */
    public static updatePost<ThrowOnError extends boolean = false>(options: Options<UpdatePostData, ThrowOnError>): RequestResult<UpdatePostResponses, UpdatePostErrors, ThrowOnError> {
        return (options.client ?? client).patch<UpdatePostResponses, UpdatePostErrors, ThrowOnError>({
            responseValidator: async (data) => await zUpdatePostResponse.parseAsync(data),
            url: '/posts/{post_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Default {
    /**
     * Health
     */
    public static health<ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
            responseValidator: async (data) => await zHealthResponse.parseAsync(data),
            url: '/health',
            ...options
        });
    }
}
