// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Comment
 */
export type Comment = {
    /**
     * Post Id
     */
    post_id: number;
    /**
     * Author
     */
    author: string;
    /**
     * Body
     */
    body: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Post Id
     */
    post_id: number;
    /**
     * Author
     */
    author: string;
    /**
     * Body
     */
    body: string;
};

/**
 * CommentUpdate
 */
export type CommentUpdate = {
    /**
     * Body
     */
    body?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Post
 */
export type Post = {
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PostCreate
 */
export type PostCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
};

/**
 * PostUpdate
 */
export type PostUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Body
     */
    body?: string | null;
};

/**
 * User
 */
export type User = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersResponses = {
    /**
     * Response Listusers
     *
     * Successful Response
     */
    200: Array<User>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListPostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/posts';
};

export type ListPostsResponses = {
    /**
     * Response Listposts
     *
     * Successful Response
     */
    200: Array<Post>;
};

export type ListPostsResponse = ListPostsResponses[keyof ListPostsResponses];

export type CreatePostData = {
    body: PostCreate;
    path?: never;
    query?: never;
    url: '/posts';
};

export type CreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
    /**
     * Successful Response
     */
    201: Post;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type DeletePostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type DeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePostError = DeletePostErrors[keyof DeletePostErrors];

export type DeletePostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePostResponse = DeletePostResponses[keyof DeletePostResponses];

export type GetPostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type GetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
    /**
     * Successful Response
     */
    200: Post;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type UpdatePostData = {
    body: PostUpdate;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type UpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePostError = UpdatePostErrors[keyof UpdatePostErrors];

export type UpdatePostResponses = {
    /**
     * Successful Response
     */
    200: Post;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type ListCommentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/comments';
};

export type ListCommentsResponses = {
    /**
     * Response Listcomments
     *
     * Successful Response
     */
    200: Array<Comment>;
};

export type ListCommentsResponse = ListCommentsResponses[keyof ListCommentsResponses];

export type CreateCommentData = {
    body: CommentCreate;
    path?: never;
    query?: never;
    url: '/comments';
};

export type CreateCommentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCommentError = CreateCommentErrors[keyof CreateCommentErrors];

export type CreateCommentResponses = {
    /**
     * Successful Response
     */
    201: Comment;
};

export type CreateCommentResponse = CreateCommentResponses[keyof CreateCommentResponses];

export type DeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/comments/{comment_id}';
};

export type DeleteCommentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCommentError = DeleteCommentErrors[keyof DeleteCommentErrors];

export type DeleteCommentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCommentResponse = DeleteCommentResponses[keyof DeleteCommentResponses];

export type GetCommentData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/comments/{comment_id}';
};

export type GetCommentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCommentError = GetCommentErrors[keyof GetCommentErrors];

export type GetCommentResponses = {
    /**
     * Successful Response
     */
    200: Comment;
};

export type GetCommentResponse = GetCommentResponses[keyof GetCommentResponses];

export type UpdateCommentData = {
    body: CommentUpdate;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/comments/{comment_id}';
};

export type UpdateCommentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCommentError = UpdateCommentErrors[keyof UpdateCommentErrors];

export type UpdateCommentResponses = {
    /**
     * Successful Response
     */
    200: Comment;
};

export type UpdateCommentResponse = UpdateCommentResponses[keyof UpdateCommentResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Response Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];
