// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Post
 */
export const zPost = z.object({
    title: z.string().min(1).max(200),
    body: z.string().min(1).max(2000),
    id: z.int(),
    created_at: z.iso.datetime()
});

/**
 * PostCreate
 */
export const zPostCreate = z.object({
    title: z.string().min(1).max(200),
    body: z.string().min(1).max(2000)
});

/**
 * PostUpdate
 */
export const zPostUpdate = z.object({
    title: z.string().min(1).max(200).nullish(),
    body: z.string().min(1).max(2000).nullish()
});

/**
 * User
 */
export const zUser = z.object({
    name: z.string().min(1).max(100),
    email: z.email(),
    id: z.int(),
    created_at: z.iso.datetime()
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
    name: z.string().min(1).max(100),
    email: z.email()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    name: z.string().min(1).max(100).nullish(),
    email: z.email().nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * Response Listusers
 *
 * Successful Response
 */
export const zListUsersResponse = z.array(zUser);

export const zCreateUserBody = zUserCreate;

/**
 * Successful Response
 */
export const zCreateUserResponse = zUser;

export const zDeleteUserPath = z.object({
    user_id: z.int()
});

/**
 * Successful Response
 */
export const zDeleteUserResponse = z.void();

export const zGetUserPath = z.object({
    user_id: z.int()
});

/**
 * Successful Response
 */
export const zGetUserResponse = zUser;

export const zUpdateUserBody = zUserUpdate;

export const zUpdateUserPath = z.object({
    user_id: z.int()
});

/**
 * Successful Response
 */
export const zUpdateUserResponse = zUser;

/**
 * Response Listposts
 *
 * Successful Response
 */
export const zListPostsResponse = z.array(zPost);

export const zCreatePostBody = zPostCreate;

/**
 * Successful Response
 */
export const zCreatePostResponse = zPost;

export const zDeletePostPath = z.object({
    post_id: z.int()
});

/**
 * Successful Response
 */
export const zDeletePostResponse = z.void();

export const zGetPostPath = z.object({
    post_id: z.int()
});

/**
 * Successful Response
 */
export const zGetPostResponse = zPost;

export const zUpdatePostBody = zPostUpdate;

export const zUpdatePostPath = z.object({
    post_id: z.int()
});

/**
 * Successful Response
 */
export const zUpdatePostResponse = zPost;

/**
 * Response Health
 *
 * Successful Response
 */
export const zHealthResponse = z.record(z.string(), z.string());
